### ISSUE TITLE
Skipping the last listbox item?

### ISSUE THREAD

**Issue by edmundito** [ericoporto/arrowselect#4] opened 2024-07-24 18:32 UTC
Hello, great module!

I may have needed help selecting items from a list box. For whatever reason, it skips the last item for me and goes directly to the button.

Here's what my GUI looks like:

![image](https://github.com/user-attachments/assets/dd119c98-cf08-4898-8934-5f6f946a38a0)

**Comment by edmundito** [comment] 2024-07-24 18:41
Looking at the module in detail, looks like the problem may lie here:

https://github.com/ericoporto/arrowselect/blob/23fcfbfc81af19672b60187b115352a63ca24e21/arrowselect.asc#L51

Let's say I have five items. The value returned will be 4 instead because the topItem is 0. Just curious why that -1 is needed...

**Comment by ericoporto** [comment] 2024-07-25 01:43
Well it looks all my old code ages terribly as I don't know either, I will need to run it and figure it out why it gives such error.

It looks like that code is meant for some issue of figuring it out how many lines are actually visible in the list box and I think it does some assumption that you can scroll the list box and have a partial number of lines shown - like say it has 5 lines but 7 items it would be possible to scroll in a way say to have only 2 items, which I don't know if it's possible or not.

Just in case this is behavior change between 3 and 4 - I don't know, I am typing this on my phone so I don't have my computer right now to test - which AGS version did you tested the above GUI?

> curious why that -1 is needed...

That may simply be a mistake but I am not completely sure without checking.

---

Oh btw, my hotspot code assumes the hotspot is convex so it doesn't work if the hotspot isn't - I guess I need to document this too.

**Comment by edmundito** [comment] 2024-07-25 16:33
I'm using AGS 3.6.1.

**Comment by ericoporto** [comment] 2024-07-25 19:38
I confirmed that removing the -1 fixes the issue.

Edit: made a new release that just removes the minus one.

**Comment by ericoporto** [comment] 2024-08-19 22:51
This was fixed in https://github.com/ericoporto/arrowselect/commit/067694a2cecb7b2c905c3e5362db7d62a6202712 and the last release already has this fix in.

**Closed as completed by ericoporto** 2024-08-19 22:51 UTC
